The-Outlaws/cindr2

client/components/game.js, client/game/config.js, client/game/main.js, client/game/scenes/questionRoom.js, package-lock.json, package.json
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
added a game directory and some boilerplate code for phaser implementation
=> feat: broken phaser sync

server/db/models/answer.js, server/db/models/index.js, server/db/models/question.js, server/db/models/room.js, server/db/models/user.js
=> feat: Added all models

public/manifest.json, server/db/models/index.js
Added manifest
Fixed sequelize association user to user {as: Match, through: UserMatch}
=> #1 migration

client/components/loginForm.js, client/components/profile.js, client/components/signupForm.js, client/store/user.js
New User info lives on store and is rendered in profile component
=> feature: new user lives in store

client/game/scenes/Boot.js, client/game/scenes/questionRoom.js, client/game/sprites/Background.js
- Fixed game background sizing issue
=> Background Image Fixed

client/game/scenes/questionRoom.js
Collision is currently a bit buggy as the scene render layers scenes (same function triggers a new scene when it's a simple click event, though).
=> feat: collision between answer and sprite changes scene

client/game/scenes/questionRoom.js, public/index.html, public/style.css
add font size and potential game font (not working tho)
=> added font style

public/style.css
added scroll overflow for profile/signup and flex box formatting
=> feat: changed form styling

client/components/profile.js, client/components/signupForm.js, public/style.css, script/seed.js, server/db/models/user.js
- added error handling to signup component - should tell user if the user was not created (ie status 500) or if it already exists (ie status 401) 
- changed model and seed data so that height could be a string, so that users can enter their height in a format familiar to them (ie no more "what's my height in inches?") - remember to re-run npm run seed for this 
- edited CSS file to style the upload photo box to look a bit more like a button 
- added an inclusivity note for orientation and gender fields
=> Errorhandling

client/game/scenes/DestinationRoom.js, client/game/scenes/DestinationRoom2.js, client/game/scenes/Splash.js, client/game/scenes/TrollHole.js, client/game/scenes/questionRoom.js
Minor tweak to Phaser scenes - added CollideWorldBounds so that avatar stays within the screen
=> feature: added boundaries for avatar to stay within screen

client/components/matchChannel.js, client/components/matches.js, client/components/matchesList.js, client/components/message.js, client/components/messagesList.js, client/components/newMessageEntry.js, client/routes.js, client/socket.js, client/store/index.js, client/store/reducers/messages.js, public/style.css, script/seed.js, server/api/conversations.js, server/api/messages.js, server/socket/index.js
MATCHES AND CHAT AND MESSAGES LOAD!! need to add sockets and post messages next...
npm run seed
first, then login:
login: petra@email.com
password: 123password
=> feat: basic chats rendered between users and matches

client/components/matchChannel.js, client/components/matches.js, client/components/matchesList.js, client/components/message.js, client/components/messagesList.js, client/components/newMessageEntry.js, client/socket.js, client/store/index.js, client/store/reducers/messages.js, public/style.css, script/seed.js, server/api/conversations.js, server/api/messages.js, server/socket/index.js
=> #7 chat continued

client/components/matchChannel.js, client/components/matches.js, client/components/matchesList.js, client/components/message.js, client/components/messagesList.js, client/components/newMessageEntry.js, client/routes.js, client/store/reducers/user.js
refactored react/connect exports
redirect on logout
=> #8 refactor react

client/components/avatarForm.js, client/components/signupForm.js, public/style.css
-Added drop down options for age & height selections
-Ensure user information is still updating correctly in database
-Adjusted css to look more uniform & work with drop downs
=> added drop downs for age and height

client/components/matchesList.js, client/components/messagesList.js, script/seed.js
added more seed data NPM RUN SEED
incoming match request viewable
CHORE: need to add button functionality to change isaccepted and isrejected values
=> feat: can view incoming match request profile

client/components/matches.js, client/components/matchesList.js, client/components/message.js, client/components/messagesList.js, client/components/newMessageEntry.js, client/store/reducers/conversations.js, client/store/reducers/index.js, public/style.css, server/api/conversations.js
=> #9 match request

script/seed.js
added a few more background images
=> some new images

client/components/game.js, client/game/main.js, client/game/scenes/Splash.js, client/game/scenes/TrollHole.js, server/auth/index.js
=> fix: scene adjustments, barely

client/components/messagesList.js, public/style.css, server/api/users.js, server/auth/index.js
order of rooms is correct now!!
=> fix: ordered by create join table

client/game/scenes/QuestionFive.js, client/game/scenes/QuestionFour.js, client/game/scenes/QuestionOne.js, client/game/scenes/QuestionTwo.js, client/game/scenes/Splash.js
updated some text and part of splash page
=> feature: splash and some text

client/game/main.js, client/game/scenes/Boot.js, client/game/scenes/QuestionEight.js, client/game/scenes/QuestionEleven.js, client/game/scenes/QuestionFive.js, client/game/scenes/QuestionFour.js, client/game/scenes/QuestionNine.js, client/game/scenes/QuestionNineteen.js, client/game/scenes/QuestionSeventeen.js, client/game/scenes/QuestionSixteen.js, public/style.css
=> feature: adjusted more text

client/game/main.js, client/game/scenes/QuestionEighteen.js, client/game/scenes/QuestionFive.js, client/game/scenes/QuestionNineteen.js, client/game/scenes/QuestionTen.js, client/game/scenes/QuestionTwentyOne.js, public/style.css
=> feature: updated some more text

client/store/reducers/conversations.js, script/seed.js, server/api/conversations.js
chat bugs all fixed! duplicate requests and 2 way requests not permittted
=> fix: conversation bugs all fixed

client/components/profile.js, public/style.css
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> styling font profile
